### ISSUE TITLE
Minecraft Recipe Problem

### ISSUE THREAD

**Issue by salaoc** [MSathieu/CraftableMobs#1]
There was this mod called silkspawners (https://minecraft.curseforge.com/projects/silk-spawners-forge-edition). Before I go over that, the problem is, that when I install his mod, the crafting feature of the spawner no longer works, I think he said something about json recipes although I don't know anything about that. He tried everything in his power to fix my problem but he said he can't fix it. He said it's probably something on Forge's part. Although, other parts of your mod works fine, like crafting the spawn_egg and changing spawners to a different mob and such. I don't know if you can do anything about that or if it's something that only Forge can fix, but I'm just letting you know.

**Comment by jredfox** [comment]
https://github.com/MSathieu/CraftableMobs/pull/2/files

**Comment by jredfox** [comment]
if you merged the commit close this issue
