### ISSUE TITLE
Minecraft failed to start

### ISSUE THREAD

**Issue by Chancho91** [MSathieu/CraftableMobs#5]
Here is the crash report I got when trying to start Minecraft.
[crash-2019-06-27_12.30.52-client.txt](https://github.com/MSathieu/CraftableMobs/files/3335785/crash-2019-06-27_12.30.52-client.txt)

**Comment by MSathieu** [comment]
The game starts fine on my computer, could you check which mod conflicts with CraftableMobs so I can try to fix it?

**Comment by Chancho91** [comment]
I loaded the game with just this mod and it still crashes. It might be the version of forge I'm using. Which version should I use instead? 
[crash-2019-06-28_21.04.12-client.txt](https://github.com/MSathieu/CraftableMobs/files/3341253/crash-2019-06-28_21.04.12-client.txt)

**Comment by MSathieu** [comment]
Sorry, forgot to update my forge version and that broke it on newer versions. Going to update it on curseforge to fix this.
