### ISSUE TITLE
No config file?

### ISSUE THREAD

**Issue by aimbait** [MSathieu/CraftableMobs#6]
I have OCD and this mod is great, one thing that prevents me from using it, however, is that it adds a crafting recipe for the spawner and the puts the Spawn Eggs in a new creative tab. I looked in my config folder and couldn't find squat for this mod. Is there no config?

**Comment by MSathieu** [comment]
There is indeed no config file, but why don't you want it in the creative tab?

**Comment by MSathieu** [comment]
I could add a config option for the spawner recipe though.

**Comment by aimbait** [comment]
I

> There is indeed no config file, but why don't you want it in the creative tab?

It's an OCD thing, I have a modpack which only features very fluff-less simple mods that are close to vanilla. This mod is perfect, minus the creative tab part. I want my pack to feel as vanilla-y as possible, and a creative tab breaks that. If this could be toggleable in config, this mod would be perfect. Thanks for speedy response.

**Comment by ChrisGiov** [comment]
This mod does not work. I can't craft the spawner with iron bars.
